### ISSUE TITLE
报错了,信息如下

### ISSUE THREAD

**Issue by faithererer** [Most3R-03/SDUT_xxcj#1]
```
Traceback (most recent call last):
  File "D:\Download\SDUT_xxcj-main\sdut_xxcj.py", line 520, in <module>
    make_print_to_file(path="./log")   #进行print日志输出，
  File "D:\Download\SDUT_xxcj-main\sdut_xxcj.py", line 106, in make_print_to_file
    sys.stdout = Logger(create_detail_day() + '.log', path=path)
  File "D:\Download\SDUT_xxcj-main\sdut_xxcj.py", line 97, in __init__
    self.log = open(os.path.join(path, filename), "a", encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: './log\\day2022_07_26.log'
```

**Comment by faithererer** [comment]
我把第520行删了就可以啦
```
   make_print_to_file(path="./log")   #进行print日志输出，
```

**Comment by Most3R-03** [comment]
那行代码是保存日志的，在目录创建一个log的文件夹就不会报错了。

**Comment by faithererer** [comment]
好的谢谢
